Update soft-crud.repository.base.ts
sourcefuse/loopback4-soft-delete pull request #37
Opened 2021-06-24 17:43 UTC by arnaud16571542

Replace buggy where manipulation, trying to impose delete:false, with FilterBuilder & WhereBuilder

## Description
Fixes #35 

## Type of change
- [X ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested ?
Manually tested

## Checklist:
- [X ] Performed a self-review of my own code

2021-06-25 07:50 UTC, akshatdubeysf commented on src/repositories/soft-crud.repository.base.ts
> +    return super.findOne(fb.build(), options);
@arnaud16571542 The findOneIncludeSoftDelete is missing?

2021-06-30 11:40 UTC, samarpan-b requested changes

2021-06-30 11:40 UTC, samarpan-b commented on src/repositories/soft-crud.repository.base.ts
> -  findAll(filter?: Filter<T>, options?: Options): Promise<(T & Relations)[]> {
need this method

2021-06-30 11:40 UTC, samarpan-b commented on src/repositories/soft-crud.repository.base.ts
> -  async findByIdIncludeSoftDelete(
need this method

2022-07-06 10:37 UTC, akshatdubeysf commented
This has been implemented through another PR.

2022-07-06 10:37 UTC, closed without merging